In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("all_data.csv")

In [56]:
df.head()

,age,analysis_module,average_thickness,cd_area_ratio,center_thickness,cup_area,cup_volume,dataset_id,disc_area,etdrs_center,...,fixation,horizontal_dd,linear_cdr,patient_id,report_title,rim_area,rim_volume,total_volume,vertical_cdr,vertical_dd
0,38,RETINA,"278,9",NaN,85.0,NaN,NaN,0,NaN,202.0,...,2,NaN,NaN,Абдуллаева,3D Macula Report,NaN,NaN,"7,88",NaN,NaN
1,38,RETINA,"250,6",NaN,191.0,NaN,NaN,1,NaN,219.0,...,2,NaN,NaN,Абдуллаева,3D Macula Report,NaN,NaN,"7,08",NaN,NaN
2,38,NFL,NaN,"0,66",NaN,"1,35","0,32",1,"2,04",NaN,...,1,"1,50","0,81",Абдуллаева,3D Disc Report w/ Topography,"0,69","0,05",NaN,"0,70","1,81"
3,38,NFL,NaN,"0,70",NaN,"1,33","0,32",1,"1,90",NaN,...,1,"1,42","0,84",Абдуллаева,3D Disc Report w/ Topography,"0,57","0,04",NaN,"0,76","1,73"
4,38,NFL,NaN,"0,66",NaN,"1,30","0,31",1,"1,98",NaN,...,1,"1,45","0,81",Абдуллаева,3D Disc Report w/ Topography,"0,68","0,05",NaN,"0,71","1,77"

In [59]:
df_retina = df[df['analysis_module']=='RETINA']
df_retina = df_retina.drop(["cd_area_ratio", "cup_area", "cup_volume", "disc_area", "horizontal_dd", "linear_cdr", "rim_area", "rim_volume", "vertical_cdr", "vertical_dd"], axis=1)
df_retina

,age,analysis_module,average_thickness,center_thickness,dataset_id,etdrs_center,etdrs_inI,etdrs_inN,etdrs_inS,etdrs_inT,etdrs_outI,etdrs_outN,etdrs_outS,etdrs_outT,eye,fastq,fixation,patient_id,report_title,total_volume
0,38,RETINA,"278,9",85.0,0,202.0,315.0,303.0,303.0,304.0,288.0,266.0,269.0,271.0,0,16,2,Абдуллаева,3D Macula Report,"7,88"
1,38,RETINA,"250,6",191.0,1,219.0,276.0,266.0,270.0,273.0,249.0,242.0,246.0,246.0,1,53,2,Абдуллаева,3D Macula Report,"7,08"
13,68,RETINA,"152,4",205.0,1,167.0,147.0,171.0,240.0,156.0,179.0,60.0,181.0,155.0,1,21,2,Абрамкина,3D Macula Report,"4,31"
14,68,RETINA,"218,1",188.0,1,210.0,239.0,234.0,237.0,226.0,230.0,216.0,207.0,201.0,1,40,2,Абрамкина,3D Macula Report,"6,16"
15,64,RETINA,"278,2",196.0,0,233.0,286.0,302.0,292.0,281.0,283.0,272.0,278.0,272.0,0,42,2,Авдеев,3D Macula Report,"7,86"
16,64,RETINA,"281,1",191.0,1,231.0,290.0,296.0,288.0,279.0,292.0,279.0,281.0,271.0,1,43,2,Авдеев,3D Macula Report OU,"7,95"
17,64,RETINA,"276,5",201.0,0,235.0,287.0,301.0,290.0,280.0,283.0,270.0,271.0,272.0,0,42,2,Авдеев,3D Macula Report,"7,81"
18,64,RETINA,"279,6",190.0,1,230.0,289.0,296.0,289.0,277.0,290.0,277.0,278.0,270.0,1,42,2,Авдеев,3D Macula Report,"7,90"
19,64,RETINA,"281,1",191.0,1,231.0,290.0,296.0,288.0,279.0,292.0,279.0,281.0,271.0,1,43,2,Авдеев,3D Macula Report,"7,95"
20,69,RETINA,"218,9",203.0,1,217.0,238.0,234.0,234.0,225.0,229.0,216.0,207.0,205.0,1,37,2,Абрамкина,3D Macula Report,"6,17"
21,74,RETINA,"255,7",161.0,1,217.0,291.0,298.0,296.0,286.0,263.0,233.0,255.0,233.0,1,41,2,Абдурахмедова,3D Macula Report OU,"7,23"
22,74,RETINA,"243,9",162.0,0,219.0,283.0,288.0,286.0,280.0,249.0,227.0,231.0,225.0,0,40,2,Абдурахмедова,3D Macula Report,"6,89"
23,74,RETINA,"255,7",161.0,1,217.0,291.0,298.0,296.0,286.0,263.0,233.0,255.0,233.0,1,41,2,Абдурахмедова,3D Macula Report,"7,23"
24,70,RETINA,"216,1",171.0,1,193.0,237.0,235.0,234.0,225.0,217.0,217.0,207.0,208.0,1,37,2,Абрамкина,3D Macula Report,"6,11"
25,70,RETINA,"216,8",173.0,1,194.0,238.0,235.0,236.0,225.0,220.0,211.0,212.0,207.0,1,39,2,Абрамкина,3D Macula Report,"6,13"
26,62,RETINA,"286,0",333.0,1,327.0,291.0,369.0,294.0,282.0,325.0,256.0,282.0,232.0,1,44,2,Авдонин,3D Macula Report,"8,00"
27,62,RETINA,"282,8",225.0,1,279.0,334.0,356.0,304.0,289.0,317.0,272.0,258.0,238.0,1,38,2,Авдонин,3D Macula Report,"7,99"
28,64,RETINA,"272,0",214.0,1,273.0,303.0,330.0,320.0,297.0,287.0,244.0,264.0,241.0,1,39,2,Авдонин,3D Macula Report,"7,67"

In [ ]:
df_retina.to_csv("retina_data.csv")

In [64]:
df_nfl = df[df['analysis_module']=='NFL']
#Столбцы для RETINA
df_nfl = df_nfl.drop(["average_thickness", "center_thickness", "etdrs_inT", "etdrs_outI", "etdrs_outN", "etdrs_outS", "etdrs_outT", "etdrs_center", "etdrs_inI", "etdrs_inN", "etdrs_inS", "total_volume"], axis=1)
df_nfl = df_nfl.drop("report_title", axis=1)
df_nfl

,age,analysis_module,cd_area_ratio,cup_area,cup_volume,dataset_id,disc_area,eye,fastq,fixation,horizontal_dd,linear_cdr,patient_id,rim_area,rim_volume,vertical_cdr,vertical_dd
2,38,NFL,"0,66","1,35","0,32",1,"2,04",1,51,1,"1,50","0,81",Абдуллаева,"0,69","0,05","0,70","1,81"
3,38,NFL,"0,70","1,33","0,32",1,"1,90",1,42,1,"1,42","0,84",Абдуллаева,"0,57","0,04","0,76","1,73"
4,38,NFL,"0,66","1,30","0,31",1,"1,98",1,43,1,"1,45","0,81",Абдуллаева,"0,68","0,05","0,71","1,77"
5,38,NFL,"0,28","0,57","0,11",0,"2,02",0,20,1,"1,54","0,53",Абдуллаева,"1,45","0,18","0,43","1,74"
6,38,NFL,"0,41","0,88","0,19",0,"2,12",0,25,1,"1,59","0,64",Абдуллаева,"1,24","0,17","0,68","1,73"
7,63,NFL,"0,68","2,19","0,65",0,"3,24",0,29,1,"1,87","0,82",Абрамова,"1,05","0,08","0,75","2,19"
8,63,NFL,"0,69","2,11","0,54",0,"3,07",0,56,1,"1,79","0,83",Абрамова,"0,96","0,08","0,74","2,26"
9,63,NFL,"0,87","3,16","0,94",1,"3,63",1,25,1,"2,01","0,93",Абрамова,"0,47","0,01","0,94","2,26"
10,63,NFL,"0,86","3,22","0,88",1,"3,75",1,31,1,"2,04","0,93",Абрамова,"0,52","0,02","0,95","2,26"
11,63,NFL,"0,88","2,98","0,83",1,"3,37",1,30,1,"1,95","0,94",Абрамова,"0,39","0,01","0,93","2,21"
12,63,NFL,"0,85","3,13","0,88",1,"3,67",1,30,1,"2,04","0,92",Абрамова,"0,54","0,02","0,94","2,29"

In [ ]:
df_nfl.to_csv("nfl_data.csv")

In [ ]:
df_info = pd.read_csv("all_data_info.csv")

In [62]:
df_info.head()

,CircleDirection,ColorMapAnterior,ColorMode,DayBirth,EqualReportOpt,EthnicGroup,FundusOverlay,FundusSelect,GridSelection,MagnifyImage,...,PatientLastName,PatientMiddleName,Sex,SliceH,SliceV,ThicknessSelect,TypeReportOpt,YearBirth,dEyeMagniValue,type
0,-1,-1,0,20,-1,white,0,-1,1,-1,...,Абдуллаева,NaN,2,64,256,-1,-1,1979,"1,007577",2
1,-1,-1,0,20,-1,white,0,-1,1,-1,...,Абдуллаева,NaN,2,64,256,-1,-1,1979,"1,007577",2
2,1,-1,0,20,-1,white,-1,-1,-1,-1,...,Абдуллаева,NaN,2,-1,-1,-1,-1,1979,"1,007577",5
3,1,-1,0,20,-1,white,-1,-1,-1,-1,...,Абдуллаева,NaN,2,-1,-1,-1,-1,1979,"1,007577",5
4,1,-1,0,20,-1,white,-1,-1,-1,-1,...,Абдуллаева,NaN,2,-1,-1,-1,-1,1979,"1,007577",5